version: '2'
services:
  openconfig_cassini_1:
    build: ./emulator-oc-cassini
    ports:
      - "11002:830"
  openconfig_cassini_2:
    build: ./emulator-oc-cassini
    ports:
      - "11003:830"
  tapi_ols:
    build: ./emulator-tapi-2.1
    ports:
      - "11001:1234"
